[package]
name = "rusted_iron_ring"
version = "0.1.0"
authors = ["Dece <shgck@pistache.land>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
nom = "5"
